### ISSUE TITLE
Provide upgrade instructions for CLI for windows and ubuntu

### ISSUE THREAD

**Issue by depombo** [iasql/docs#17]
- [ ] windows
- [ ] ubuntu

**Comment by dfellis** [comment]
They should both be easy. Just repeating the install instructions will overwrite the old install. But that means they're both still two commands and not one like with homebrew.

Fixing that will take some effort.

**Comment by depombo** [comment]
> They should both be easy. Just repeating the install instructions will overwrite the old install. But that means they're both still two commands and not one like with homebrew.
> 
> Fixing that will take some effort.

Oh nice then I will probably close this out and make a note/subtask/checkbox in https://github.com/iasql/cli/issues/12 ?

**Comment by depombo** [comment]
we will be deprecating the CLI so closing this for now
